# Generated by Django 6.1.1 on 2026-10-02 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('escuela', 'Escuela'), ('servicios', 'Servicios'), ('entretenimiento', 'Entretenimiento'), ('salud', 'Salud'), ('compras', 'Compras'), ('otros', 'Otros')], max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
